### ISSUE TITLE
can't restore the generated tf model?

### ISSUE THREAD

**Issue by fye881** [dalgu90/resnet-18-tensorflow#2]
Hi,
I downloaded the model (t7 file), installed torchfile, and run "python extract_torch_t7.py". I got 3 files under init/:
-rw-r--r-- 1  domain^users     3277 Nov 17 10:29 model.ckpt.index
-rw-r--r-- 1  domain^users 46782116 Nov 17 10:29 model.ckpt.data-00000-of-00001
-rw-r--r-- 1  domain^users       77 Nov 17 10:29 checkpoint
-rw-r--r-- 1  domain^users 47121651 Nov 17 10:29 model.ckpt.meta

I then tried to load them in python:
 with tf.Session() as sess:
    saver = tf.train.import_meta_graph('init/model.ckpt.meta')
    saver.restore(sess, 'init/model.ckpt')

Traceback (most recent call last):
  File "<stdin>", line 3, in <module>
  File "~/tensorflow/tensorflow_ve/local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1439, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "~/tensorflow/tensorflow_ve/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 767, in run
    run_metadata_ptr)
  File "~/tensorflow/tensorflow_ve/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 965, in _run
    feed_dict_string, options, run_metadata)
  File "~/tensorflow/tensorflow_ve/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1015, in _do_run
    target_list, options, run_metadata)
  File "~/tensorflow/tensorflow_ve/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1035, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Cannot assign a device to node 'tower_0/conv5_2/bn_2/cond/pred_id_3': Could not satisfy explicit device specification '/device:GPU:0' because no devices matching that specification are registered in this process; available devices: /job:localhost/replica:0/task:0/cpu:0
	 [[Node: tower_0/conv5_2/bn_2/cond/pred_id_3 = Identity[T=DT_BOOL, _device="/device:GPU:0"](is_train_3)]]

Caused by op u'tower_0/conv5_2/bn_2/cond/pred_id_3', defined at:
  File "<stdin>", line 2, in <module>
  File "~/tensorflow/tensorflow_ve/local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1577, in import_meta_graph
    **kwargs)
  File "~/tensorflow/tensorflow_ve/local/lib/python2.7/site-packages/tensorflow/python/framework/meta_graph.py", line 498, in import_scoped_meta_graph
    producer_op_list=producer_op_list)
  File "~/tensorflow/tensorflow_ve/local/lib/python2.7/site-packages/tensorflow/python/framework/importer.py", line 287, in import_graph_def
    op_def=op_def)
  File "~/tensorflow/tensorflow_ve/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2395, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "~/tensorflow/tensorflow_ve/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1264, in __init__
    self._traceback = _extract_stack()

InvalidArgumentError (see above for traceback): Cannot assign a device to node 'tower_0/conv5_2/bn_2/cond/pred_id_3': Could not satisfy explicit device specification '/device:GPU:0' because no devices matching that specification are registered in this process; available devices: /job:localhost/replica:0/task:0/cpu:0
	 [[Node: tower_0/conv5_2/bn_2/cond/pred_id_3 = Identity[T=DT_BOOL, _device="/device:GPU:0"](is_train_3)]]

**Comment by dalgu90** [comment]
Thanks for your interest in the repo.

It seems that the graph needs to be assigned to GPU:0 but your machine does not have any GPU, so you got this error.
If you want to run the graph on CPU, first extract the model ckpt with the model build on CPU.
(Change L94 of `resnet.py` to have `tf.device('/CPU:0')`, then run `extract_torch_t7.py`)
Then the meta-graph will be restored.
