### ISSUE TITLE
Key conv1/bn/beta/Momentum not found in checkpoint

### ISSUE THREAD

**Issue by abramjos** [dalgu90/resnet-18-tensorflow#7]
Hi,

nice work. 
 I was using the train.py to train the model using the imagenet weights.
NotFoundError (see above for traceback): Restoring from checkpoint failed. This is most likely due to a Variable name or other graph key that is missing from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:
I am getting the following error at time. I have checked the variables they are all good to go.

```
Key conv1/bn/beta/Momentum not found in checkpoint
	 [[{{node save/RestoreV2}} = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_INT32, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]
	 [[{{node save/restore_all/NoOp_1/_10}} = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_447_save/restore_all/NoOp_1", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]

```

**Comment by kalybz** [comment]
when I run extract_torch_t7.py .I have a trouble that "Open ResNet-18 torch checkpoint: E:/BS/resnet-18-tensorflow-master/resnet-18-tensorflow-master/resnet-18.t7
Traceback (most recent call last):
  File "E:/BS/resnet-18-tensorflow-master/resnet-18-tensorflow-master/extract_torch_t7.py", line 20, in <module>
    o = torchfile.load(T7_PATH)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\torchfile.py", line 424, in load
    return reader.read_obj()
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\torchfile.py", line 370, in read_obj
    obj._obj = self.read_obj()
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\torchfile.py", line 387, in read_obj
    obj[k] = v
TypeError: unhashable type: 'numpy.ndarray'"
do you have some advices for me ?thank you .

**Comment by linmoxiaomo** [comment]
@kalybz I have the same problem. Have you fixed it yet?  Thank you
